version: '3.8'

services:
  web:
    build: .
    command: bash -c "bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: realworld_api_development
      MYSQL_PASSWORD: password
  db:
    image: mysql:8.2.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: realworld_api_development
      # MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
