default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: root
  password: root_password
  database: realworld_api_development


development:
  <<: *default
  database: realworld_api_development

test:
  <<: *default
  database: realworld_api_test

# production:
#   <<: *default
#   adapter: mysql2
#   database: realworld-api_production
#   username: root
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   socket: /var/lib/mysql/mysql.sock
#   encoding: utf8mb4

production:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  host: aws-test.c1qyy8cwqfh4.ap-northeast-1.rds.amazonaws.com
  database: realworld_api_production



