# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   host: db
#   username: root
#   password: root_password
#   database: realworld_api_development


# development:
#   <<: *default
#   database: realworld_api_development

# test:
#   <<: *default
#   database: realworld_api_test

# production:
#   <<: *default
#   adapter: mysql2
#   database: realworld-api_production
#   username: root
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   socket: /var/lib/mysql/mysql.sock
#   encoding: utf8mb4

# production:
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password: <%= ENV['DATABASE_PASSWORD'] %> 
#   host: realworld-api-217-web.cxqykcy8u0vh.ap-northeast-1.rds.amazonaws.com
#   database: realworld_api_production
  

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: aws-test.c1qyy8cwqfh4.ap-northeast-1.rds.amazonaws.com
  username: admin
  password: password
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: realworld_api_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: realworld_api_test
#
production:
  <<: *default
  database: realworld_api_production
  username: realworld_api
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>